###############################################################################
# Cloud Build Pipeline — Math Content Engine
#
# Separate pipeline for the content engine (different git repo from tutor).
#
# Triggers:
# - Push to main: Deploy to staging
# - Tag v*.*.*: Deploy to production
# - PR: Run tests only
###############################################################################

substitutions:
  _REGION: us-central1
  _ENV: dev
  _APP_NAME: math-tutor
  _IMAGE_TAG: ${SHORT_SHA}

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  ###########################################################################
  # Step 1: Run Engine Tests
  ###########################################################################
  - name: 'python:3.12-slim'
    id: 'engine-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y --no-install-recommends ffmpeg libcairo2 libpango-1.0-0 > /dev/null 2>&1
        pip install ".[dev,api]" redis httpx --quiet
        pytest tests/ -v --tb=short --junitxml=test-results/engine-junit.xml
    waitFor: ['-']

  ###########################################################################
  # Step 2: Build Engine Image
  ###########################################################################
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-engine'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/content-engine:${_IMAGE_TAG}'
      - '-f'
      - 'docker/Dockerfile.engine'
      - '.'
    waitFor: ['engine-tests']

  ###########################################################################
  # Step 3: Push Engine Image
  ###########################################################################
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-engine'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/content-engine:${_IMAGE_TAG}'
    waitFor: ['build-engine']

  ###########################################################################
  # Step 4: Deploy to Cloud Run
  ###########################################################################
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-engine'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_APP_NAME}-content-engine-${_ENV}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/content-engine:${_IMAGE_TAG}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--cpu=4'
      - '--memory=4Gi'
      - '--timeout=600'
      - '--concurrency=10'
      - '--update-env-vars=ENVIRONMENT=${_ENV},PUBLISH_EVENTS=true'
    waitFor: ['push-engine']

# Artifacts
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-build-artifacts/builds/${BUILD_ID}'
    paths:
      - 'test-results/*.xml'

# Build timeout
timeout: '1800s'

# Images
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/content-engine:${_IMAGE_TAG}'
