"""
LLM-Generated Narrated Animation

This example demonstrates the full pipeline:
1. LLM generates the Manim animation code
2. LLM generates teacher-quality narration script
3. TTS converts narration to speech
4. Final video combines animation + voice

The narration is generated by the LLM as an excellent teacher would speak,
not manually written.

Requirements:
    - ANTHROPIC_API_KEY or OPENAI_API_KEY environment variable
    - pip install edge-tts

Run:
    python examples/llm_narrated_animation.py

Output:
    tests/test_output/llm_narrated_linear_equation.mp4
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))


def main():
    """Generate animation with LLM-generated narration."""
    import tempfile
    from dotenv import load_dotenv

    load_dotenv()

    output_dir = Path(__file__).parent.parent / "tests" / "test_output"
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 70)
    print("LLM-Generated Narrated Math Animation")
    print("=" * 70)

    # Initialize the engine
    from math_content_engine import MathContentEngine, Config
    from math_content_engine.tts import (
        NarrationScriptGenerator,
        NarratedAnimationGenerator,
        VoiceStyle,
        convert_script_to_animation_script,
    )

    config = Config()
    engine = MathContentEngine(config)

    # =========================================================================
    # STEP 1: Generate Manim Animation Code with LLM
    # =========================================================================
    print("\n[1/4] Generating Manim animation code with LLM...")

    topic = "Solving the linear equation 2x + 3 = 7"
    animation_result = engine.generate(
        topic=topic,
        requirements="""
        Create a clear, educational animation that:
        1. Shows the equation 2x + 3 = 7 prominently
        2. Demonstrates subtracting 3 from both sides
        3. Shows the simplified equation 2x = 4
        4. Demonstrates dividing both sides by 2
        5. Reveals the solution x = 2
        6. Verifies the answer by substitution

        IMPORTANT:
        - Use Text() instead of MathTex() to avoid LaTeX dependency
        - Make each step visible for at least 4 seconds
        - Total animation should be about 35-40 seconds
        - Use colors to highlight important elements
        - Add smooth transitions between steps
        """,
        audience_level="middle school",
        output_filename="temp_animation"
    )

    if not animation_result.success:
        print(f"Error generating animation: {animation_result.error_message}")
        return

    print(f"   Animation generated: {animation_result.video_path}")
    print(f"   Scene: {animation_result.scene_name}")

    # =========================================================================
    # STEP 2: Generate Narration Script with LLM
    # =========================================================================
    print("\n[2/4] Generating teacher narration script with LLM...")

    narration_generator = NarrationScriptGenerator(engine.llm_client)

    # Get video duration
    import subprocess
    duration_cmd = [
        "ffprobe", "-v", "error",
        "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1",
        str(animation_result.video_path)
    ]
    duration_result = subprocess.run(duration_cmd, capture_output=True, text=True)
    animation_duration = float(duration_result.stdout.strip()) if duration_result.returncode == 0 else 35.0

    print(f"   Animation duration: {animation_duration:.1f} seconds")

    # Generate narration script using LLM
    generated_script = narration_generator.generate_for_equation(
        equation="2x + 3 = 7",
        solution_steps=[
            "Show the original equation",
            "Subtract 3 from both sides to get 2x = 4",
            "Divide both sides by 2 to get x = 2",
            "Verify: 2(2) + 3 = 4 + 3 = 7 ✓"
        ],
        animation_duration=animation_duration,
        audience_level="middle school"
    )

    print(f"\n   Generated {len(generated_script.cues)} narration cues:")
    print("-" * 50)
    for i, cue in enumerate(generated_script.cues):
        print(f"   [{cue.time:5.1f}s] {cue.text}")
    print("-" * 50)

    # =========================================================================
    # STEP 3: Convert to TTS and Combine
    # =========================================================================
    print("\n[3/4] Converting narration to speech (Teacher voice)...")

    # Convert generated script to AnimationScript format
    animation_script = convert_script_to_animation_script(generated_script)

    # Create narrated video with teacher voice
    narrator = NarratedAnimationGenerator(voice=VoiceStyle.TEACHER_FEMALE)

    print(f"   Voice: {VoiceStyle.TEACHER_FEMALE.value}")

    # =========================================================================
    # STEP 4: Generate Final Video
    # =========================================================================
    print("\n[4/4] Combining animation with narration...")

    output_path = output_dir / "llm_narrated_linear_equation.mp4"

    result = narrator.create_narrated_video(
        video_path=animation_result.video_path,
        script=animation_script,
        output_path=output_path
    )

    if result.success:
        print(f"\n{'=' * 70}")
        print("SUCCESS!")
        print(f"{'=' * 70}")
        print(f"\nOutput: {result.video_path}")
        print(f"\nThe narration was generated by AI as an excellent teacher would speak!")
        print(f"\nPlay with: open {result.video_path}")
    else:
        print(f"\nError: {result.error_message}")


def demo_narration_generation_only():
    """
    Demo: Generate narration script without video.

    Useful for previewing what the LLM generates.
    """
    from dotenv import load_dotenv
    load_dotenv()

    from math_content_engine import MathContentEngine
    from math_content_engine.tts import NarrationScriptGenerator

    print("=" * 70)
    print("Demo: LLM Narration Script Generation")
    print("=" * 70)

    engine = MathContentEngine()
    generator = NarrationScriptGenerator(engine.llm_client)

    # Example 1: Linear equation
    print("\n--- Example 1: Linear Equation ---")
    script1 = generator.generate_for_equation(
        equation="3x - 5 = 10",
        solution_steps=[
            "Add 5 to both sides",
            "Get 3x = 15",
            "Divide by 3",
            "Solution: x = 5"
        ],
        animation_duration=30.0,
        audience_level="middle school"
    )

    print(f"\nGenerated narration for: {script1.title}")
    for cue in script1.cues:
        print(f"  [{cue.time:5.1f}s] {cue.text}")

    # Example 2: Concept explanation
    print("\n--- Example 2: Concept Explanation ---")
    script2 = generator.generate_for_concept(
        concept="Slope of a Line",
        key_points=[
            "Slope measures steepness",
            "Calculated as rise over run",
            "Positive slope goes up, negative goes down",
            "Zero slope is horizontal"
        ],
        animation_duration=40.0,
        audience_level="high school"
    )

    print(f"\nGenerated narration for: {script2.title}")
    for cue in script2.cues:
        print(f"  [{cue.time:5.1f}s] {cue.text}")


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == "--demo":
        demo_narration_generation_only()
    else:
        main()
