"""
FastAPI server setup for video retrieval API.
"""

import logging
import os
from pathlib import Path
from typing import Optional

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from .routes import router, set_storage
from .storage import VideoStorage

logger = logging.getLogger(__name__)


def create_app(
    db_path: Optional[Path] = None,
    cors_origins: Optional[list] = None,
) -> FastAPI:
    """
    Create and configure the FastAPI application.

    Args:
        db_path: Path to SQLite database. Defaults to MATH_ENGINE_DB_PATH env var
                 or ./data/videos.db
        cors_origins: List of allowed CORS origins. Defaults to ["*"]

    Returns:
        Configured FastAPI application
    """
    # Configure database path
    if db_path is None:
        db_path = Path(os.getenv("MATH_ENGINE_DB_PATH", "./data/videos.db"))

    # Initialize storage
    storage = VideoStorage(db_path)
    set_storage(storage)

    # Create FastAPI app
    app = FastAPI(
        title="Math Content Engine - Video API",
        description=(
            "REST API for retrieving math animation videos generated by the "
            "Math Content Engine. Videos can be retrieved by ID along with "
            "their metadata including topic, generation settings, and performance metrics."
        ),
        version="1.0.0",
        docs_url="/docs",
        redoc_url="/redoc",
    )

    # Configure CORS
    if cors_origins is None:
        cors_origins = os.getenv("MATH_ENGINE_CORS_ORIGINS", "*").split(",")

    app.add_middleware(
        CORSMiddleware,
        allow_origins=cors_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # Include routes
    app.include_router(router)

    # Include playground routes
    from .playground import playground_router

    app.include_router(playground_router)

    # Serve playground frontend as static files
    static_dir = Path(__file__).parent.parent / "static" / "playground"
    if static_dir.exists():
        app.mount(
            "/playground",
            StaticFiles(directory=str(static_dir), html=True),
            name="playground",
        )

    # Health check endpoint
    @app.get("/health")
    async def health_check() -> dict:
        """Health check endpoint."""
        return {"status": "healthy", "service": "math-content-engine-api"}

    # Root endpoint
    @app.get("/")
    async def root() -> dict:
        """Root endpoint with API info."""
        return {
            "name": "Math Content Engine - Video API",
            "version": "1.0.0",
            "docs": "/docs",
            "playground": "/playground/",
            "endpoints": {
                "list_videos": "GET /api/v1/videos",
                "get_video": "GET /api/v1/videos/{id}",
                "get_video_file": "GET /api/v1/videos/{id}/file",
                "get_video_code": "GET /api/v1/videos/{id}/code",
                "create_video": "POST /api/v1/videos",
                "delete_video": "DELETE /api/v1/videos/{id}",
                "stats": "GET /api/v1/videos/stats/summary",
                "playground_config": "GET /api/v1/playground/config",
                "playground_interests": "GET /api/v1/playground/interests",
                "playground_prompts": "POST /api/v1/playground/prompts/preview",
                "playground_execute": "POST /api/v1/playground/execute",
            }
        }

    logger.info(f"API server initialized with database at {db_path}")
    return app


def run_server(
    host: str = "0.0.0.0",
    port: int = 8000,
    db_path: Optional[Path] = None,
    reload: bool = False,
) -> None:
    """
    Run the API server using uvicorn.

    Args:
        host: Host to bind to
        port: Port to bind to
        db_path: Path to SQLite database
        reload: Enable auto-reload for development
    """
    import uvicorn

    # Set db_path in environment for the app factory
    if db_path:
        os.environ["MATH_ENGINE_DB_PATH"] = str(db_path)

    uvicorn.run(
        "math_content_engine.api.server:create_app",
        host=host,
        port=port,
        reload=reload,
        factory=True,
    )


# Create default app instance for uvicorn
app = create_app()


if __name__ == "__main__":
    run_server()
